local:
  image: wemeep/wemeep-users-service
#  image: usersservice
  ports:
    - "8080:8080"
  links:
    - mongo:db

mongo:
  image: mongo:latest
  restart: always
  privileged: true
  container_name: db
  volumes:
    - ./mongo/data:/data
  ports:
    - "27017:27017"
    - "28017:28017"
  environment:
    - MONGO_USER
    - MONGO_PASS
  cap_add:
    - SYS_RESOURCE

mongogui:
  image: aegypius/genghis
  ports:
    - "5000:5000"
  links:
    - mongo:db
